apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy02
  labels:
    app: autodeploy02
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718788860443
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy02
  template:
    metadata:
      labels:
        app: autodeploy02
    spec:
      containers:
        - name: autodeploy02
          image: acrworkflow1718788860443.azurecr.io/image-workflow-1718788860443:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
