apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployXX
  labels:
    app: autodeployXX
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718787934616
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployXX
  template:
    metadata:
      labels:
        app: autodeployXX
    spec:
      containers:
        - name: autodeployXX
          image: acrworkflow1718787934616.azurecr.io/image-workflow-1718787934616:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
