apiVersion: v1
kind: Service
metadata:
  name: autodeployXX
  namespace: namespace-workflow-1718787934616
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeployXX
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000